# Misc variables
remote_user: devuser
host_file_path: /apps/ansible/inventory/hosts
java_source: https://nexus.int.corp.sun/service/local/repositories/inhouse/content/au/com/suncorp/easyshare/java/jdk/1.8.0_60/jdk-1.8.0_60.tar.gz
java_version: 1.8.0_60                              # required to direct the application to the correct JDK to use -> /apps/java/jdk{{java_version}}/bin
java_install_dir: /apps/java
rds_ssl_cert: rds-ca-2015-ap-southeast-2.pem


# Application variables
app_name: helloworld                                 # application name, used for designating ELB's
hostname_prefix: EFSRD                              # prefix for hostnames
#hosts: easyshare                                    # group heading in inventory, these need to exist in the inventory before specifiying them here TODO: make play to do this??
#old_hosts: easyshare-old                            # group heading in inventory, these need to exist in the inventory before specifiying them here
artifact_nexus_url:
service_install_dir: "/apps/{{app_name}}/"          # directory on host to install application
artifact_name: "{{app_name}}"-LATEST.war            # any name that you prefer for the artifact
#start_script: start_easyshare.sh                    # start script file name
#stop_script: stop_easyshare.sh                      # stop script file name
splunk_log_path: "/apps/{{app_name}}/easyshareLog.*.log" # name of splunk logs to ingest
splunk_index: easyshare_test
splunk_sourcetype: easyshare_api
liquibase_masterlog_directory: src/main/resources/config/liquibase/master.xml  # default directory for liquidbase


# EC2 variables
image: ami-15dc962f               # check here for up-to-date images http://confluence.int.corp.sun/confluence/display/AWS/Deploying+in+EC2#DeployinginEC2-AMICatalogue
region: ap-southeast-2
instance_type: m3.medium
PUB_SSH_KEY: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
workspace: W-001082               # W-001082(EasySuite Pre-prod workspace)
timeout: 2500                     # number of seconds to wait for server to become accessable before timing out