swagger:
    title: Sample API
    description: Sample API!
    version: 0.0.1
    termsOfServiceUrl: http://google.com/
    contact:
    license: Apache 2.0
    licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html

server:
    tomcat:
        basedir: tomcat
        max-threads: 200
        access-log-enabled: true
        access-log-pattern: "%h %{X-Forwarded-For}i %l %u %t %r %s %b %D"

security:
  basic:
    enabled: false

spring:
  application:
    name: app # Prevents the leaking of information in response header X-Application-Context
    index: 0 # Prevents the leaking of information in response headers X-Application-Context