server:
    port: 8080
    ssl:
        key-store: keystore.p12
        key-store-password: password
        keyStoreType: PKCS12
        keyAlias: tomcat

endpoints:
    enabled: false
    health:
        enabled: true

spring:
    profiles:
        active: uat
